// SPDX-License-Identifier: GPL-3.0-or-later
#include "import_export.hpp"

#include "../344_sexpr/sexpr.hpp"

#include <cmath>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <set>
#include <sstream>
#include <string>
#include <unordered_map>

namespace import_export {

using kicad_model::Board;
using kicad_model::Footprint;
using kicad_model::Pad;
using kicad_model::PcbTrack;
using kicad_model::PcbVia;
using kicad_model::GrLine;
using kicad_model::NetInfo;
using kicad_model::ItemType;

namespace {

std::string mm(double v) {
    std::ostringstream os;
    os.precision(4);
    os << std::fixed << v;
    // Strip trailing zeros.
    std::string s = os.str();
    while (!s.empty() && s.back() == '0') s.pop_back();
    if (!s.empty() && s.back() == '.') s.pop_back();
    return s;
}

// World-space pad center in mm.
std::pair<double,double> pad_world_mm(const Footprint & fp, const Pad & p) {
    double a = fp.angle.rad();
    double c = std::cos(a), s = std::sin(a);
    double lx = geom::nm_to_mm(p.at.x), ly = geom::nm_to_mm(p.at.y);
    double wx = geom::nm_to_mm(fp.at.x) + lx * c - ly * s;
    double wy = geom::nm_to_mm(fp.at.y) + lx * s + ly * c;
    return { wx, wy };
}

} // namespace

// ==================== Specctra DSN ====================

std::string to_dsn(const Board & board, const DsnOptions & opts) {
    std::ostringstream os;
    if (opts.header_comments) {
        os << "; Specctra DSN generated by ac9/import_export\n";
    }
    os << "(pcb ac9_generated_board\n";
    // (parser) block.
    os << "  (parser\n"
       << "    (string_quote \")\n"
       << "    (space_in_quoted_tokens on)\n"
       << "    (host_cad ac9)\n"
       << "    (host_version 0.1)\n"
       << "  )\n";
    // (resolution).
    os << "  (resolution um " << opts.resolution_um << ")\n";
    // (unit).
    os << "  (unit mm)\n";
    // (structure): layer stackup + board outline.
    os << "  (structure\n";
    for (const auto & L : board.layers) {
        if (L.type != "signal") continue;
        os << "    (layer " << L.canonical_name
           << " (type signal))\n";
    }
    // Board outline: emit all Edge.Cuts gr_line segments.
    os << "    (boundary\n";
    os << "      (path pcb 0";
    bool any = false;
    for (const auto & it : board.items) {
        if (it->type != ItemType::PcbGrLine) continue;
        const auto * g = static_cast<const GrLine *>(it.get());
        if (g->layer != "Edge.Cuts") continue;
        os << " " << mm(geom::nm_to_mm(g->start.x))
           << " " << mm(geom::nm_to_mm(g->start.y))
           << " " << mm(geom::nm_to_mm(g->end.x))
           << " " << mm(geom::nm_to_mm(g->end.y));
        any = true;
    }
    if (!any) os << " 0 0 50 0 50 30 0 30 0 0";
    os << ")\n    )\n";
    // Default rule.
    os << "    (rule\n"
       << "      (width " << mm(geom::nm_to_mm(opts.default_track_nm)) << ")\n"
       << "      (clearance 0.15)\n"
       << "      (clearance 0.15 (type default_smd))\n"
       << "      (clearance 0.15 (type smd_smd))\n"
       << "    )\n";
    os << "  )\n";

    // (placement): footprint reference designators.
    os << "  (placement\n";
    for (const auto & it : board.items) {
        if (it->type != ItemType::PcbFootprint) continue;
        const auto * fp = static_cast<const Footprint *>(it.get());
        std::string ref;
        for (const auto & f : fp->fields) if (f.name == "Reference") { ref = f.value; break; }
        if (ref.empty()) ref = fp->uuid.substr(0, 8);
        os << "    (component " << fp->lib_id << "\n"
           << "      (place " << ref << " "
                << mm(geom::nm_to_mm(fp->at.x)) << " "
                << mm(geom::nm_to_mm(fp->at.y)) << " "
                << (fp->placement_layer == "B.Cu" ? "back" : "front") << " "
                << fp->angle.deg() << ")\n"
           << "    )\n";
    }
    os << "  )\n";

    // (library): footprint image definitions with pins.
    os << "  (library\n";
    std::set<std::string> emitted_libs;
    for (const auto & it : board.items) {
        if (it->type != ItemType::PcbFootprint) continue;
        const auto * fp = static_cast<const Footprint *>(it.get());
        if (!emitted_libs.insert(fp->lib_id).second) continue;
        os << "    (image " << fp->lib_id << "\n";
        for (const auto & p : fp->pads) {
            os << "      (pin " << (p.shape == "circle" ? "Round" : "Rect")
               << (p.shape == "circle"
                    ? "[T]Pad_" + mm(geom::nm_to_mm(p.size.x))
                    : "[T]Pad_" + mm(geom::nm_to_mm(p.size.x)) + "x" + mm(geom::nm_to_mm(p.size.y)))
               << " " << p.number << " "
               << mm(geom::nm_to_mm(p.at.x)) << " "
               << mm(geom::nm_to_mm(p.at.y)) << ")\n";
        }
        os << "    )\n";
    }
    // Padstack definitions: minimal generic.
    std::set<std::pair<std::string,long long>> padstacks;
    for (const auto & it : board.items) {
        if (it->type != ItemType::PcbFootprint) continue;
        const auto * fp = static_cast<const Footprint *>(it.get());
        for (const auto & p : fp->pads)
            padstacks.emplace(p.shape == "circle" ? "Round" : "Rect", p.size.x);
    }
    for (const auto & ps : padstacks) {
        os << "    (padstack ";
        if (ps.first == "Round")
            os << "Round[T]Pad_" << mm(geom::nm_to_mm(ps.second))
               << " (shape (circle F.Cu " << mm(geom::nm_to_mm(ps.second)) << "))\n"
               << "               (shape (circle B.Cu " << mm(geom::nm_to_mm(ps.second)) << "))\n"
               << "               (attach off))\n";
        else
            os << "Rect[T]Pad_" << mm(geom::nm_to_mm(ps.second)) << "x" << mm(geom::nm_to_mm(ps.second))
               << " (shape (rect F.Cu -" << mm(geom::nm_to_mm(ps.second)/2)
               << " -" << mm(geom::nm_to_mm(ps.second)/2)
               << " " << mm(geom::nm_to_mm(ps.second)/2)
               << " " << mm(geom::nm_to_mm(ps.second)/2) << "))\n"
               << "               (attach off))\n";
    }
    os << "  )\n";

    // (network): nets + which pins participate.
    os << "  (network\n";
    for (const auto & n : board.nets) {
        if (n.id == 0) continue;
        os << "    (net " << n.name;
        for (const auto & it : board.items) {
            if (it->type != ItemType::PcbFootprint) continue;
            const auto * fp = static_cast<const Footprint *>(it.get());
            std::string ref;
            for (const auto & f : fp->fields) if (f.name == "Reference") { ref = f.value; break; }
            for (const auto & p : fp->pads) {
                if (p.net == n.id) os << " (pins " << ref << "-" << p.number << ")";
            }
        }
        os << ")\n";
    }
    os << "  )\n";

    // (wiring): existing tracks.
    os << "  (wiring\n";
    for (const auto & it : board.items) {
        if (it->type != ItemType::PcbTrack) continue;
        const auto * t = static_cast<const PcbTrack *>(it.get());
        os << "    (wire (path " << t->layer << " " << mm(geom::nm_to_mm(t->width_nm))
           << " " << mm(geom::nm_to_mm(t->start.x))
           << " " << mm(geom::nm_to_mm(t->start.y))
           << " " << mm(geom::nm_to_mm(t->end.x))
           << " " << mm(geom::nm_to_mm(t->end.y))
           << ") (net " << (t->net < static_cast<int>(board.nets.size()) ? board.nets[t->net].name : std::string("")) << "))\n";
    }
    os << "  )\n";
    os << ")\n";
    return os.str();
}

// ==================== Specctra SES ====================

SesResult apply_ses(Board & board, std::string_view ses_text) {
    SesResult r;
    sexpr::ParseError e;
    auto root = sexpr::parse(ses_text, &e);
    if (!root) { r.warnings = e.message; return r; }
    auto routes = root->find("routes");
    auto net_out = routes ? routes->find("network_out") : nullptr;
    if (!net_out) { r.warnings = "no network_out section"; return r; }

    // network_out contains (net "name" (wire (path L width X Y X Y ...)) ...)
    // and (via padstack X Y).
    for (const auto & n : net_out->list()) {
        if (!n->is_list() || n->head() != "net") continue;
        std::string net_name;
        if (n->size() >= 2 && n->list()[1]->is_string()) net_name = n->list()[1]->string();
        else if (n->size() >= 2 && n->list()[1]->is_atom()) net_name = n->list()[1]->atom();
        // Find or add the net in the board.
        int net_id = kicad_model::intern_net(board, net_name);

        for (const auto & c : n->list()) {
            if (!c->is_list()) continue;
            if (c->head() == "wire") {
                auto path = c->find("path");
                if (!path || path->size() < 4) continue;
                std::string layer = path->list()[1]->is_atom() ? path->list()[1]->atom() : path->list()[1]->string();
                double width_mm = path->list()[2]->as_double();
                std::vector<geom::VECTOR2I> pts;
                for (std::size_t i = 3; i + 1 < path->size(); i += 2) {
                    pts.push_back({ geom::mm_to_nm(path->list()[i]->as_double()),
                                    geom::mm_to_nm(path->list()[i + 1]->as_double()) });
                }
                for (std::size_t i = 0; i + 1 < pts.size(); ++i) {
                    auto t = std::make_shared<PcbTrack>();
                    t->start = pts[i]; t->end = pts[i + 1];
                    t->width_nm = geom::mm_to_nm(width_mm);
                    t->layer = layer;
                    t->net   = net_id;
                    t->uuid  = kicad_model::make_uuid();
                    board.items.push_back(t);
                    ++r.new_tracks;
                }
            } else if (c->head() == "via") {
                // (via padstack X Y)
                if (c->size() < 4) continue;
                double x = c->list()[2]->as_double();
                double y = c->list()[3]->as_double();
                auto v = std::make_shared<PcbVia>();
                v->at = { geom::mm_to_nm(x), geom::mm_to_nm(y) };
                v->size_nm  = geom::mm_to_nm(0.6);
                v->drill_nm = geom::mm_to_nm(0.3);
                v->net = net_id;
                v->uuid = kicad_model::make_uuid();
                board.items.push_back(v);
                ++r.new_vias;
            }
        }
    }
    r.ok = true;
    return r;
}

// ==================== IPC-2581 ====================

std::string to_ipc2581(const Board & board) {
    std::ostringstream os;
    os << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
       << "<IPC-2581 revision=\"B\" xmlns=\"http://webstds.ipc.org/2581\">\n"
       << "  <Content>\n"
       << "    <FunctionMode mode=\"ASSEMBLY\"/>\n"
       << "    <StepRef name=\"ac9_board\"/>\n"
       << "    <DictionaryStandard>\n"
       << "      <EntryStandard id=\"COPPER\"><Copper thickness=\"" << 0.035 << "\" units=\"MILLIMETER\"/></EntryStandard>\n"
       << "    </DictionaryStandard>\n"
       << "  </Content>\n"
       << "  <LogisticHeader>\n"
       << "    <Enterprise name=\"ac9\"/>\n"
       << "  </LogisticHeader>\n"
       << "  <HistoryRecord>\n"
       << "    <FileRevision revision=\"1\"/>\n"
       << "  </HistoryRecord>\n"
       << "  <Ecad name=\"tool\">\n"
       << "    <CadHeader units=\"MILLIMETER\"/>\n"
       << "    <CadData>\n"
       << "      <Layer name=\"F.Cu\"  layerFunction=\"CONDUCTOR\" side=\"TOP\" polarity=\"POSITIVE\"/>\n"
       << "      <Layer name=\"B.Cu\"  layerFunction=\"CONDUCTOR\" side=\"BOTTOM\" polarity=\"POSITIVE\"/>\n"
       << "      <Stackup>\n"
       << "        <StackupGroup name=\"Group1\">\n"
       << "          <StackupLayer layerOrGroupRef=\"F.Cu\"/>\n"
       << "          <StackupLayer layerOrGroupRef=\"B.Cu\"/>\n"
       << "        </StackupGroup>\n"
       << "      </Stackup>\n";

    // Board outline as a Polygon.
    os << "      <Step name=\"ac9_board\">\n"
       << "        <Datum x=\"0\" y=\"0\"/>\n"
       << "        <Package name=\"BOARD\">\n"
       << "          <Outline>\n            <Polygon>\n";
    for (const auto & it : board.items) {
        if (it->type != ItemType::PcbGrLine) continue;
        const auto * g = static_cast<const GrLine *>(it.get());
        if (g->layer != "Edge.Cuts") continue;
        os << "              <PolyStepSegment x=\"" << geom::nm_to_mm(g->end.x)
           << "\" y=\"" << geom::nm_to_mm(g->end.y) << "\"/>\n";
    }
    os << "            </Polygon>\n          </Outline>\n        </Package>\n";

    // Net list.
    os << "        <LogicalNet>\n";
    for (const auto & n : board.nets) {
        if (n.id == 0) continue;
        os << "          <Net name=\"" << n.name << "\"/>\n";
    }
    os << "        </LogicalNet>\n";

    // Components (footprints).
    os << "        <Component>\n";
    for (const auto & it : board.items) {
        if (it->type != ItemType::PcbFootprint) continue;
        const auto * fp = static_cast<const Footprint *>(it.get());
        std::string ref;
        for (const auto & f : fp->fields) if (f.name == "Reference") { ref = f.value; break; }
        os << "          <ComponentEntry refDes=\"" << ref
           << "\" packageRef=\"" << fp->lib_id << "\">\n"
           << "            <Location x=\"" << geom::nm_to_mm(fp->at.x)
           << "\" y=\"" << geom::nm_to_mm(fp->at.y) << "\"/>\n"
           << "          </ComponentEntry>\n";
    }
    os << "        </Component>\n";

    os << "      </Step>\n"
       << "    </CadData>\n"
       << "  </Ecad>\n"
       << "</IPC-2581>\n";
    return os.str();
}

} // namespace import_export
