// SPDX-License-Identifier: GPL-3.0-or-later
#include "schematic_capture.hpp"

#include "../341_kicad_libs/kicad_libs.hpp"

#include <array>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <mutex>
#include <random>
#include <sstream>
#include <string>
#include <unordered_map>

namespace schematic_capture {
namespace {

std::mutex g_init_mtx;
bool       g_ready = false;

constexpr const char * KIVER = "20250114";

std::string sesc(std::string_view s) {
    std::string out;
    out.reserve(s.size() + 2);
    for (char c : s) {
        switch (c) {
            case '"':  out += "\\\""; break;
            case '\\': out += "\\\\"; break;
            case '\n': out += "\\n";  break;
            default:   out += c;      break;
        }
    }
    return out;
}

std::string new_uuid() {
    static thread_local std::mt19937_64 rng(std::random_device{}());
    std::uniform_int_distribution<std::uint64_t> dist;
    std::uint64_t a = dist(rng), b = dist(rng);
    a = (a & 0xFFFFFFFFFFFF0FFFULL) | 0x0000000000004000ULL;
    b = (b & 0x3FFFFFFFFFFFFFFFULL) | 0x8000000000000000ULL;
    char buf[37];
    std::snprintf(buf, sizeof(buf),
                  "%08lx-%04lx-%04lx-%04lx-%012lx",
                  static_cast<unsigned long>((a >> 32) & 0xFFFFFFFFULL),
                  static_cast<unsigned long>((a >> 16) & 0xFFFFULL),
                  static_cast<unsigned long>(a & 0xFFFFULL),
                  static_cast<unsigned long>((b >> 48) & 0xFFFFULL),
                  static_cast<unsigned long>(b & 0xFFFFFFFFFFFFULL));
    return std::string(buf, 36);
}

std::string placeholder_lib_symbol(std::string_view lib_id) {
    std::ostringstream os;
    os << "\t\t(symbol \"" << sesc(lib_id) << "\"\n"
       << "\t\t\t(exclude_from_sim no)\n"
       << "\t\t\t(in_bom yes)\n"
       << "\t\t\t(on_board yes)\n"
       << "\t\t\t(property \"Reference\" \"?\" (at 0 0 0) (effects (font (size 1.27 1.27))))\n"
       << "\t\t\t(property \"Value\" \"" << sesc(lib_id) << "\" (at 0 -2.54 0) (effects (font (size 1.27 1.27))))\n"
       << "\t\t\t(property \"Footprint\" \"\" (at 0 0 0) (effects (font (size 1.27 1.27)) (hide yes)))\n"
       << "\t\t\t(property \"Datasheet\" \"\" (at 0 0 0) (effects (font (size 1.27 1.27)) (hide yes)))\n"
       << "\t\t\t(symbol \"" << sesc(lib_id) << "_0_1\"\n"
       << "\t\t\t\t(rectangle (start -2.54 -1.27) (end 2.54 1.27)\n"
       << "\t\t\t\t\t(stroke (width 0.254) (type default))\n"
       << "\t\t\t\t\t(fill (type background))\n"
       << "\t\t\t\t)\n"
       << "\t\t\t)\n"
       << "\t\t\t(embedded_fonts no)\n"
       << "\t\t)\n";
    return os.str();
}

std::string indent_block(std::string_view s, int tabs) {
    std::string prefix(static_cast<std::size_t>(tabs), '\t');
    std::string out;
    out.reserve(s.size() + s.size() / 32);
    bool at_line_start = true;
    for (char c : s) {
        if (at_line_start) { out += prefix; at_line_start = false; }
        out += c;
        if (c == '\n') at_line_start = true;
    }
    if (!out.empty() && out.back() != '\n') out += '\n';
    return out;
}

} // namespace

void init() {
    std::lock_guard<std::mutex> lk(g_init_mtx);
    if (g_ready) return;
    kicad_libs::init();
    g_ready = true;
}

void shutdown() {
    std::lock_guard<std::mutex> lk(g_init_mtx);
    g_ready = false;
}

Status status() {
    Status s;
    s.ready  = g_ready;
    s.detail = g_ready ? "schematic_capture initialized" : "not initialized";
    return s;
}

Result from_intent(const circuit_intent::Intent & intent, const Options & opts) {
    Result r;

    std::ostringstream out;
    out << "(kicad_sch\n"
        << "\t(version " << KIVER << ")\n"
        << "\t(generator \"" << sesc(opts.generator) << "\")\n"
        << "\t(generator_version \"" << sesc(opts.generator_version) << "\")\n"
        << "\t(uuid \"" << new_uuid() << "\")\n"
        << "\t(paper \"A4\")\n"
        << "\t(title_block\n"
        << "\t\t(title \"" << sesc(intent.title.empty() ? "tool-generated schematic" : intent.title) << "\")\n"
        << "\t\t(rev \"1\")\n"
        << "\t\t(comment 1 \"" << sesc(intent.notes) << "\")\n"
        << "\t\t(comment 2 \"generated by tool\")\n"
        << "\t)\n";

    std::vector<std::string> uniq_libids;
    std::unordered_map<std::string, bool> seen;
    for (const auto & p : intent.parts) {
        if (p.lib_hint.empty()) continue;
        if (seen.emplace(p.lib_hint, true).second) uniq_libids.push_back(p.lib_hint);
    }

    out << "\t(lib_symbols\n";
    for (const auto & lid : uniq_libids) {
        std::string block = kicad_libs::extract_symbol_block(lid);
        if (block.empty()) {
            out << placeholder_lib_symbol(lid);
            r.diagnostics.push_back({
                circuit_intent::Diagnostic::Severity::Warning,
                "lib_symbols",
                "lib symbol '" + lid + "' not found in index; placeholder emitted"
            });
            ++r.placeholder_parts;
        } else {
            out << indent_block(block, 2);
            ++r.resolved_parts;
        }
    }
    out << "\t)\n";

    int placed = 0;
    for (const auto & p : intent.parts) {
        int cols = opts.columns > 0 ? opts.columns : 5;
        int col = placed % cols;
        int row = placed / cols;
        double x = opts.origin_x_mm + col * opts.grid_pitch_mm;
        double y = opts.origin_y_mm + row * opts.grid_pitch_mm;
        ++placed;

        std::string sym_uuid = new_uuid();
        out << "\t(symbol\n"
            << "\t\t(lib_id \"" << sesc(p.lib_hint.empty() ? p.value : p.lib_hint) << "\")\n"
            << "\t\t(at " << std::fixed << std::setprecision(3) << x << " " << y << " 0)\n"
            << "\t\t(unit 1)\n"
            << "\t\t(exclude_from_sim no)\n"
            << "\t\t(in_bom yes)\n"
            << "\t\t(on_board yes)\n"
            << "\t\t(dnp " << (p.dnp ? "yes" : "no") << ")\n"
            << "\t\t(uuid \"" << sym_uuid << "\")\n"
            << "\t\t(property \"Reference\" \"" << sesc(p.ref) << "\"\n"
            << "\t\t\t(at " << x << " " << (y - 5.0) << " 0)\n"
            << "\t\t\t(effects (font (size 1.27 1.27)) (justify left))\n"
            << "\t\t)\n"
            << "\t\t(property \"Value\" \"" << sesc(p.value) << "\"\n"
            << "\t\t\t(at " << x << " " << (y + 5.0) << " 0)\n"
            << "\t\t\t(effects (font (size 1.27 1.27)) (justify left))\n"
            << "\t\t)\n"
            << "\t\t(property \"Footprint\" \"" << sesc(p.footprint_hint) << "\"\n"
            << "\t\t\t(at " << x << " " << y << " 0)\n"
            << "\t\t\t(effects (font (size 1.27 1.27)) (hide yes))\n"
            << "\t\t)\n"
            << "\t\t(property \"Datasheet\" \"" << sesc(p.datasheet_url) << "\"\n"
            << "\t\t\t(at " << x << " " << y << " 0)\n"
            << "\t\t\t(effects (font (size 1.27 1.27)) (hide yes))\n"
            << "\t\t)\n"
            << "\t\t(instances\n"
            << "\t\t\t(project \"\"\n"
            << "\t\t\t\t(path \"/" << new_uuid() << "\"\n"
            << "\t\t\t\t\t(reference \"" << sesc(p.ref) << "\")\n"
            << "\t\t\t\t\t(unit 1)\n"
            << "\t\t\t\t)\n"
            << "\t\t\t)\n"
            << "\t\t)\n"
            << "\t)\n";
    }

    double doc_x = opts.origin_x_mm + opts.columns * opts.grid_pitch_mm + 10.0;
    double doc_y = opts.origin_y_mm;
    out << "\t(text \"Nets (documentation; wiring pending):\"\n"
        << "\t\t(at " << doc_x << " " << doc_y << " 0)\n"
        << "\t\t(effects (font (size 1.6 1.6) (bold yes)) (justify left))\n"
        << "\t\t(uuid \"" << new_uuid() << "\")\n"
        << "\t)\n";
    doc_y += 3.5;
    for (const auto & n : intent.nets) {
        std::ostringstream line;
        line << (n.name.empty() ? std::string("<unnamed>") : n.name) << ": ";
        for (std::size_t i = 0; i < n.endpoints.size(); ++i) {
            if (i) line << ", ";
            line << n.endpoints[i].endpoint;
        }
        out << "\t(text \"" << sesc(line.str()) << "\"\n"
            << "\t\t(at " << doc_x << " " << doc_y << " 0)\n"
            << "\t\t(effects (font (size 1.0 1.0)) (justify left))\n"
            << "\t\t(uuid \"" << new_uuid() << "\")\n"
            << "\t)\n";
        doc_y += 2.2;
    }

    out << "\t(sheet_instances\n"
        << "\t\t(path \"/\" (page \"1\"))\n"
        << "\t)\n"
        << "\t(embedded_fonts no)\n"
        << ")\n";

    r.sch_text = out.str();
    r.ok = true;
    return r;
}

bool write_file(const std::string & path, const Result & r) {
    if (!r.ok || r.sch_text.empty()) return false;
    std::ofstream f(path, std::ios::binary);
    if (!f) return false;
    f.write(r.sch_text.data(), static_cast<std::streamsize>(r.sch_text.size()));
    return static_cast<bool>(f);
}

} // namespace schematic_capture
